# Generated by Django 3.1.2 on 2021-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20210521_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='salary',
            field=models.IntegerField(default=0, null=True, verbose_name='収入'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='spending',
            field=models.IntegerField(default=0, null=True, verbose_name='支出'),
        ),
    ]
