# Generated by Django 3.1.2 on 2021-05-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_auto_20210525_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='price',
            field=models.IntegerField(null=True, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='収入'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='spending',
            field=models.IntegerField(null=True, verbose_name='支出'),
        ),
    ]
