# Generated by Django 3.1.2 on 2021-05-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20210525_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='salary',
            new_name='income',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='price',
        ),
    ]
